In [1]:
import pandas as pd
import numpy as np
import ast

In [34]:
dc= pd.read_excel("delhi_cars.xlsx")
ch= pd.read_excel("chennai_cars.xlsx")
blr= pd.read_excel("bangalore_cars.xlsx")
kk= pd.read_excel("kolkata_cars.xlsx")
jp= pd.read_excel("jaipur_cars.xlsx")
hyd= pd.read_excel("hyderabad_cars.xlsx")

In [3]:
dc.head(5)

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [5]:
# Preprosessing delhi cars 

def json_normalize(df, column_name):
    df[column_name] = df[column_name].apply(ast.literal_eval)
    df_normalized = pd.json_normalize(df[column_name])
    df_1 = pd.concat([df, df_normalized], axis=1)
    df_1 = df_1.drop(column_name, axis=1)
    return df_1

delhi_cars_df = json_normalize(dc, 'new_car_detail')

In [6]:
delhi_cars_df

,new_car_overview,new_car_feature,new_car_specs,car_links,it,ft,bt,km,transmission,ownerNo,...,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Diesel,SUV,"10,000",Automatic,1,...,2022,7121,GTX Plus Diesel AT,â‚¹ 19 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"57,437",Manual,2,...,2016,1449,1.6 VTVT S,â‚¹ 7.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,SUV,"8,000",Automatic,1,...,2020,6837,200,â‚¹ 56 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,0,Petrol,Hatchback,"28,151",Manual,2,...,2018,10403,VXI,â‚¹ 5.23 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,SUV,"60,000",Manual,1,...,2017,5362,1.6 VTVT E Plus,â‚¹ 7.65 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,Sedan,"60,000",Automatic,1,...,2019,5627,i-VTEC CVT V,â‚¹ 9 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1481,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,SUV,"20,000",Manual,1,...,2021,8000,HTK Plus BSVI,â‚¹ 9.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1482,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,Sedan,"60,000",Manual,1,...,2011,1832,1.6 SX VTVT,â‚¹ 4.18 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1483,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Diesel,SUV,"38,000",Manual,1,...,2019,6440,1.6 SX Option Diesel,â‚¹ 11.95 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1484,"{'heading': 'Car overview', 'top': [{'key': 'I...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Diesel,SUV,"7,000",Automatic,0,...,2023,9298,Savvy 6 Str 4x4,â‚¹ 46.40 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

In [7]:
# Mapping current column names to new names
column_rename_mapping = {
    'it': 'Ignition_type',
    'ft': 'Fuel_type',
    'bt': 'Body_type',
    'km': 'Kilometers_driven',
    'transmission': 'Transmission_type',
    'ownerNo': 'Number_of_previous_owners',
    'owner': 'Ownership_details',
    'oem': 'Original_Equipment_Manufacturer',
    'model': 'Car_model',
    'modelYear': 'Year_of_car_manufacture',
    'centralVariantId': 'Central_variant_ID',
    'variantName': 'Variant_name',
    'price': 'Price_of_the_used_car',
    'priceActual': 'Actual_price',
    'priceSaving': 'Price_saving_information',
    'priceFixedText': 'Fixed price details',
    'trendingText.imgUrl': 'Image_URL',
    'trendingText.heading': 'Trending_heading',
    'trendingText.desc': 'Trending_description'
}

# Renaming columns in delhi_cars_df
delhi_cars_df.rename(columns=column_rename_mapping, inplace=True)

In [8]:
delhi_cars_df = json_normalize(delhi_cars_df, 'new_car_overview')

In [9]:
# New Dataframe to store required values
delhi_df_1 = {"Car_Info": [], "Values_for_Car_Info": [], "Image_link_of_car": []}

for index, row in delhi_cars_df.iterrows():
    for item in row['top']:
        key = item['key']
        values = item['value']
        icon = item['icon']
        delhi_df_1["Car_Info"].append(key)
        delhi_df_1["Values_for_Car_Info"].append(values)
        delhi_df_1["Image_link_of_car"].append(icon)

# Convert the dictionary to a DataFrame
delhi_df_1 = pd.DataFrame(delhi_df_1)

In [10]:
delhi_df_1

,Car_Info,Values_for_Car_Info,Image_link_of_car
0,Registration Year,2022,https://images10.gaadi.com/listing/vdp/co/v1/r...
1,Insurance Validity,Third Party insurance,https://images10.gaadi.com/listing/vdp/co/v1/i...
2,Fuel Type,Diesel,https://images10.gaadi.com/listing/vdp/co/v1/f...
3,Seats,5 Seats,https://images10.gaadi.com/listing/vdp/co/v1/s...
4,Kms Driven,"10,000 Kms",https://images10.gaadi.com/listing/vdp/co/v1/k...
...,...,...,...
14689,Seats,6 Seats,https://images10.gaadi.com/listing/vdp/co/v1/s...
14690,Kms Driven,"7,000 Kms",https://images10.gaadi.com/listing/vdp/co/v1/k...
14691,Engine Displacement,1996 cc,https://images10.gaadi.com/listing/vdp/co/v1/e...
14692,Transmission,Automatic,https://images10.gaadi.com/listing/vdp/co/v1/t...
14693,Year of Manufacture,2023,https://images10.gaadi.com/listing/vdp/co/v1/y...

In [11]:
# Dropping unwanted columns

delhi_cars_df = delhi_cars_df.drop(['top'], axis=1)

delhi_cars_df = delhi_cars_df.drop(['bottomData','heading'], axis=1)

In [13]:
delhi_cars_df = json_normalize(delhi_cars_df, 'new_car_feature')

In [14]:
# New Dataframe to store required values
delhi_df_2 = { "Features": []}

for index, row in delhi_cars_df.iterrows():
    for item in row['top']:
        values = item['value']
        delhi_df_2["Features"].append(values)

# Convert the dictionary to a DataFrame
delhi_df_2 = pd.DataFrame(delhi_df_2)

In [15]:
delhi_df_2

                       Features
0                Power Steering
1           Power Windows Front
2               Air Conditioner
3                        Heater
4        Adjustable Head Lights
...                         ...
13130    Adjustable Head Lights
13131          Fog Lights Front
13132  Anti Lock Braking System
13133              Brake Assist
13134                     Radio

[13135 rows x 1 columns]

In [16]:
# New Dataframe to store required values
delhi_df_3 = {"Comfort_and_Convenience": [], "Comfort_and_Convenience_type": []}

for index, row in delhi_cars_df.iterrows():
    for item in row['data']:
        heading = item['heading']
        values = item['list'][0]['value']
        delhi_df_3["Comfort_and_Convenience"].append(heading)
        delhi_df_3["Comfort_and_Convenience_type"].append(values)

# Convert the dictionary to a DataFrame
delhi_df_3 = pd.DataFrame(delhi_df_3)

In [17]:
delhi_df_3

            Comfort_and_Convenience Comfort_and_Convenience_type
0             Comfort & Convenience               Power Steering
1                          Interior              Air Conditioner
2                          Exterior       Adjustable Head Lights
3                            Safety     Anti Lock Braking System
4     Entertainment & Communication                        Radio
...                             ...                          ...
7212          Comfort & Convenience               Power Steering
7213                       Interior              Air Conditioner
7214                       Exterior       Adjustable Head Lights
7215                         Safety     Anti Lock Braking System
7216  Entertainment & Communication                        Radio

[7217 rows x 2 columns]

In [18]:
delhi_cars_df= delhi_cars_df.drop(['top','data'],axis=1)

In [19]:
delhi_cars_df = json_normalize(delhi_cars_df, 'new_car_specs')

In [20]:
# New Dataframe to store required values
delhi_df_4 = {"Car_Specifications": [], "Values_for_Car_Specifications": []}

for index, row in delhi_cars_df.iterrows():
    for item in row['top']:
        key=item['key']
        values = item['value']
        delhi_df_4["Car_Specifications"].append(key)
        delhi_df_4["Values_for_Car_Specifications"].append(values)


delhi_df_4 = pd.DataFrame(delhi_df_4)

In [21]:
delhi_df_4

     Car_Specifications Values_for_Car_Specifications
0               Mileage                       18 kmpl
1                Engine                       1493 CC
2             Max Power                     113.43bhp
3                Torque                         250Nm
4            Wheel Size                            17
...                 ...                           ...
8295             Engine                       1996 CC
8296          Max Power                     212.55bhp
8297             Torque                       478.5Nm
8298         Wheel Size                            19
8299              Seats                             6

[8300 rows x 2 columns]

In [22]:
# New Dataframe to store required values
delhi_df_5 = {"Feature_heading": [], "Feature_key_heading": [],"Feature_value":[]}

for index, row in delhi_cars_df.iterrows():
    for item in row['data']:
        heading = item['subHeading']
        key=item['list'][0]['key']
        values = item['list'][0]['value']
        delhi_df_5["Feature_heading"].append(heading)
        delhi_df_5["Feature_key_heading"].append(key)
        delhi_df_5["Feature_value"].append(values)

# Convert the dictionary to a DataFrame
delhi_df_5 = pd.DataFrame(delhi_df_5)

In [23]:
delhi_df_5

     Feature_heading Feature_key_heading Feature_value
0             Engine               Color          Gray
1         Dimensions              Length        4315mm
2      Miscellaneous            Gear Box       6-Speed
3             Engine               Color         White
4         Dimensions              Length        4270mm
...              ...                 ...           ...
4449      Dimensions              Length        4270mm
4450   Miscellaneous            Gear Box       6 Speed
4451          Engine               Color          Grey
4452      Dimensions              Length        4985mm
4453   Miscellaneous            Gear Box       8 Speed

[4454 rows x 3 columns]

In [24]:
delhi_cars_df=delhi_cars_df.drop(['top','data'],axis=1)

In [25]:
# Merging all DataFrames


delhi_cars_df = pd.merge(delhi_cars_df, delhi_df_1, how='left', left_index=True, right_index=True)

delhi_cars_df = pd.merge(delhi_cars_df, delhi_df_2, how='left', left_index=True, right_index=True)

delhi_cars_df = pd.merge(delhi_cars_df, delhi_df_3, how='left', left_index=True, right_index=True)

delhi_cars_df = pd.merge(delhi_cars_df, delhi_df_4, how='left', left_index=True, right_index=True)

delhi_cars_df = pd.merge(delhi_cars_df, delhi_df_5, how='left', left_index=True, right_index=True)

In [30]:
delhi_cars_df

,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,Car_model,Year_of_car_manufacture,...,Values_for_Car_Info,Features,Comfort_and_Convenience,Comfort_and_Convenience_type,Car_Specifications,Values_for_Car_Specifications,Feature_heading,Feature_key_heading,Feature_value,city
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,...,2022,Power Steering,Comfort & Convenience,Power Steering,Mileage,18 kmpl,Engine,Color,Gray,Delhi
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,...,Third Party insurance,Power Windows Front,Interior,Air Conditioner,Engine,1493 CC,Dimensions,Length,4315mm,Delhi
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,...,Diesel,Air Conditioner,Exterior,Adjustable Head Lights,Max Power,113.43bhp,Miscellaneous,Gear Box,6-Speed,Delhi
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,...,5 Seats,Heater,Safety,Anti Lock Braking System,Torque,250Nm,Engine,Color,White,Delhi
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,...,"10,000 Kms",Adjustable Head Lights,Entertainment & Communication,Radio,Wheel Size,17,Dimensions,Length,4270mm,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,0,Petrol,Sedan,"60,000",Automatic,1,1st Owner,Honda,Honda City,2019,...,"34,568 Kms",Power Adjustable Exterior Rear View Mirror,Safety,Anti Lock Braking System,Seats,5,Miscellaneous,Gear Box,7 Speed DCT,Delhi
1481,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Kia,Kia Sonet,2021,...,DL6C,Electric Folding Rear View Mirror,Entertainment & Communication,Cd Player,Mileage,12.04 kmpl,Engine,Color,Others,Delhi
1482,0,Petrol,Sedan,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Verna,2011,...,Second Owner,Anti Lock Braking System,Comfort & Convenience,Power Steering,Engine,1996 CC,Dimensions,Length,4490mm,Delhi
1483,0,Diesel,SUV,"38,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2019,...,1197 cc,Brake Assist,Interior,Air Conditioner,Max Power,212.55bhp,Miscellaneous,Gear Box,4 Speed,Delhi
1484,0,Diesel,SUV,"7,000",Automatic,0,0th Owner,MG,MG Gloster,2023,...,Manual,Radio,Exterior,Adjustable Head Lights,Torque,478.5Nm,Engine,Color,Pearl White,Delhi

In [27]:
delhi_cars_df['city']= 'Delhi'

In [29]:
delhi_cars_df=delhi_cars_df.drop(['car_links','Image_link_of_car'],axis=1)

In [31]:
# Saving cleaned data
delhi_cars_df.to_excel('Final_Delhi_cars_list.xlsx')

In [40]:
# # Preprosessing kolkata cars 

def json_normalize(df, column_name):
    import ast
    df[column_name] = df[column_name].apply(ast.literal_eval)
    df_normalized = pd.json_normalize(df[column_name])
    df_1 = pd.concat([df, df_normalized], axis=1)
    df_1 = df_1.drop(column_name, axis=1)
    return df_1

hyd_cars_df = json_normalize(hyd, 'new_car_detail')


# Mapping current column names to new names
column_rename_mapping = {
    'it': 'Ignition_type',
    'ft': 'Fuel_type',
    'bt': 'Body_type',
    'km': 'Kilometers_driven',
    'transmission': 'Transmission_type',
    'ownerNo': 'Number_of_previous_owners',
    'owner': 'Ownership_details',
    'oem': 'Original_Equipment_Manufacturer',
    'model': 'Car_model',
    'modelYear': 'Year_of_car_manufacture',
    'centralVariantId': 'Central_variant_ID',
    'variantName': 'Variant_name',
    'price': 'Price_of_the_used_car',
    'priceActual': 'Actual_price',
    'priceSaving': 'Price_saving_information',
    'priceFixedText': 'Fixed price details',
    'trendingText.imgUrl': 'Image_URL',
    'trendingText.heading': 'Trending_heading',
    'trendingText.desc': 'Trending_description'
}


hyd_cars_df.rename(columns=column_rename_mapping, inplace=True)





hyd_cars_df = json_normalize(hyd_cars_df, 'new_car_overview')

# new Dataframe to store required values
hyd_df_1 = {"Car_Info": [], "Values_for_Car_Info": [], "Image_link_of_car": []}

for index, row in hyd_cars_df.iterrows():
    for item in row['top']:
        key = item['key']
        values = item['value']
        icon = item['icon']
        hyd_df_1["Car_Info"].append(key)
        hyd_df_1["Values_for_Car_Info"].append(values)
        hyd_df_1["Image_link_of_car"].append(icon)


hyd_df_1 = pd.DataFrame(hyd_df_1)



# Droping unwanted columns
hyd_cars_df = hyd_cars_df.drop(['top'], axis=1)

hyd_cars_df = hyd_cars_df.drop(['bottomData','heading'], axis=1)





hyd_cars_df = json_normalize(hyd_cars_df, 'new_car_feature')


# Creating a new Dataframe to store required values
hyd_df_2 = { "Features": []}

for index, row in hyd_cars_df.iterrows():
    for item in row['top']:
        values = item['value']
        hyd_df_2["Features"].append(values)


hyd_df_2 = pd.DataFrame(hyd_df_2)






# new Dataframe to store required values
hyd_df_3 = {"Comfort_and_Convenience": [], "Comfort_and_Convenience_type": []}

for index, row in hyd_cars_df.iterrows():
    for item in row['data']:
        heading = item['heading']
        values = item['list'][0]['value']
        hyd_df_3["Comfort_and_Convenience"].append(heading)
        hyd_df_3["Comfort_and_Convenience_type"].append(values)


hyd_df_3 = pd.DataFrame(hyd_df_3)

hyd_cars_df=hyd_cars_df.drop(['top','data'],axis=1)





hyd_cars_df = json_normalize(hyd_cars_df, 'new_car_specs')


# new Dataframe to store required values
hyd_df_4 = {"Car_Specifications": [], "Values_for_Car_Specifications": []}

for index, row in hyd_cars_df.iterrows():
    for item in row['top']:
        key=item['key']
        values = item['value']
        hyd_df_4["Car_Specifications"].append(key)
        hyd_df_4["Values_for_Car_Specifications"].append(values)


hyd_df_4 = pd.DataFrame(hyd_df_4)





# new Dataframe to store required values
hyd_df_5 = {"Feature_heading": [], "Feature_key_heading": [],"Feature_value":[]}

for index, row in hyd_cars_df.iterrows():
    for item in row['data']:
        heading = item['subHeading']
        key=item['list'][0]['key']
        values = item['list'][0]['value']
        hyd_df_5["Feature_heading"].append(heading)
        hyd_df_5["Feature_key_heading"].append(key)
        hyd_df_5["Feature_value"].append(values)

 
hyd_df_5 = pd.DataFrame(hyd_df_5)

hyd_cars_df = hyd_cars_df.drop(['top','data'], axis=1)

In [41]:
# Merging all DataFrames


hyd_cars_df = pd.merge(hyd_cars_df, hyd_df_1, how='left', left_index=True, right_index=True)

hyd_cars_df = pd.merge(hyd_cars_df, hyd_df_2, how='left', left_index=True, right_index=True)

hyd_cars_df = pd.merge(hyd_cars_df, hyd_df_3, how='left', left_index=True, right_index=True)

hyd_cars_df = pd.merge(hyd_cars_df, hyd_df_4, how='left', left_index=True, right_index=True)

hyd_cars_df = pd.merge(hyd_cars_df, hyd_df_5, how='left', left_index=True, right_index=True)

In [42]:
hyd_cars_df

,car_links,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,Car_model,...,Values_for_Car_Info,Image_link_of_car,Features,Comfort_and_Convenience,Comfort_and_Convenience_type,Car_Specifications,Values_for_Car_Specifications,Feature_heading,Feature_key_heading,Feature_value
0,https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"20,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Polo,...,2022,https://images10.gaadi.com/listing/vdp/co/v1/r...,Power Steering,Comfort & Convenience,Power Steering,Mileage,16.47 kmpl,Engine,Color,Others
1,https://www.cardekho.com/buy-used-car-details/...,0,Petrol,Hatchback,"85,582",Manual,2,2nd Owner,Hyundai,Hyundai EON,...,Third Party insurance,https://images10.gaadi.com/listing/vdp/co/v1/i...,Power Windows Front,Interior,Air Conditioner,Engine,999 CC,Dimensions,Length,3971mm
2,https://www.cardekho.com/used-car-details/used...,0,Petrol,SUV,"10,000",Manual,1,1st Owner,Hyundai,Hyundai Venue,...,Petrol,https://images10.gaadi.com/listing/vdp/co/v1/f...,Air Conditioner,Exterior,Adjustable Head Lights,Max Power,108.62bhp,Miscellaneous,Gear Box,6 Speed
3,https://www.cardekho.com/buy-used-car-details/...,0,Petrol,Hatchback,"50,750",Manual,1,1st Owner,Maruti,Maruti Baleno,...,5 Seats,https://images10.gaadi.com/listing/vdp/co/v1/s...,Heater,Safety,Anti Lock Braking System,Torque,175nm,Engine,Color,Red
4,https://www.cardekho.com/used-car-details/used...,0,Petrol,SUV,"10,000",Automatic,1,1st Owner,Mahindra,Mahindra Thar,...,"20,000 Kms",https://images10.gaadi.com/listing/vdp/co/v1/k...,Adjustable Head Lights,Entertainment & Communication,Radio,Wheel Size,R16,Dimensions,Length,3495mm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,https://www.cardekho.com/used-car-details/used...,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Mahindra,Mahindra XUV500,...,Second Owner,https://images10.gaadi.com/listing/vdp/co/v1/o...,Bluetooth,Comfort & Convenience,Power Steering,Torque,90Nm,Dimensions,Length,4620mm
1479,https://www.cardekho.com/used-car-details/used...,0,Diesel,Sedan,"50,000",Automatic,1,1st Owner,Jaguar,Jaguar XF,...,1197 cc,https://images10.gaadi.com/listing/vdp/co/v1/e...,Power Steering,Interior,Air Conditioner,Wheel Size,13,Miscellaneous,Gear Box,7 Speed
1480,https://www.cardekho.com/used-car-details/used...,0,Diesel,Sedan,"1,20,000",Automatic,3,3rd Owner,BMW,BMW 5 Series,...,Manual,https://images10.gaadi.com/listing/vdp/co/v1/t...,Power Windows Front,Exterior,Adjustable Head Lights,Seats,5,Engine,Color,Silver
1481,https://www.cardekho.com/used-car-details/used...,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Tata,Tata Nexon,...,2017,https://images10.gaadi.com/listing/vdp/co/v1/y...,Air Conditioner,Safety,Centeral Locking,Mileage,19.83 kmpl,Dimensions,Length,3985mm
1482,https://www.cardekho.com/used-car-details/used...,0,Diesel,MUV,"1,00,000",Manual,1,1st Owner,Toyota,Toyota Innova,...,Oct 2010,https://images10.gaadi.com/listing/vdp/co/v1/r...,Heater,Entertainment & Communication,Cd Player,Engine,1198 CC,Miscellaneous,Gear Box,5 Speed

In [43]:
hyd_cars_df['city']='Hyderabad'

In [44]:
hyd_cars_df=hyd_cars_df.drop(['car_links','Image_link_of_car'],axis=1)

In [45]:
# Saving cleaned data
hyd_cars_df.to_excel('Final_Hyderabad_cars_list.xlsx')

In [46]:
# Preprosessing jaipur cars 

def json_normalize(df, column_name):
    import ast
    df[column_name] = df[column_name].apply(ast.literal_eval)
    df_normalized = pd.json_normalize(df[column_name])
    df_1 = pd.concat([df, df_normalized], axis=1)
    df_1 = df_1.drop(column_name, axis=1)
    return df_1

jaipur_cars_df = json_normalize(jp, 'new_car_detail')

In [47]:
# Mapping current column names to new names

column_rename_mapping = {
    'it': 'Ignition_type',
    'ft': 'Fuel_type',
    'bt': 'Body_type',
    'km': 'Kilometers_driven',
    'transmission': 'Transmission_type',
    'ownerNo': 'Number_of_previous_owners',
    'owner': 'Ownership_details',
    'oem': 'Original_Equipment_Manufacturer',
    'model': 'Car_model',
    'modelYear': 'Year_of_car_manufacture',
    'centralVariantId': 'Central_variant_ID',
    'variantName': 'Variant_name',
    'price': 'Price_of_the_used_car',
    'priceActual': 'Actual_price',
    'priceSaving': 'Price_saving_information',
    'priceFixedText': 'Fixed price details',
    'trendingText.imgUrl': 'Image_URL',
    'trendingText.heading': 'Trending_heading',
    'trendingText.desc': 'Trending_description'
}


jaipur_cars_df.rename(columns=column_rename_mapping, inplace=True)

In [48]:
jaipur_cars_df = json_normalize(jaipur_cars_df, 'new_car_overview')


# New Dataframe to store required values
jaipur_df_1 = {"Car_Info": [], "Values_for_Car_Info": [], "Image_link_of_car": []}

for index, row in jaipur_cars_df.iterrows():
    for item in row['top']:
        key = item['key']
        values = item['value']
        icon = item['icon']
        jaipur_df_1["Car_Info"].append(key)
        jaipur_df_1["Values_for_Car_Info"].append(values)
        jaipur_df_1["Image_link_of_car"].append(icon)


jaipur_df_1 = pd.DataFrame(jaipur_df_1)

In [49]:
# Droping unwanted columns
jaipur_cars_df = jaipur_cars_df.drop(['top'], axis=1)

jaipur_cars_df = jaipur_cars_df.drop(['bottomData','heading'], axis=1)

In [50]:
jaipur_cars_df = json_normalize(jaipur_cars_df, 'new_car_feature')

# new Dataframe to store required values
jaipur_df_2 = { "Features": []}

for index, row in jaipur_cars_df.iterrows():
    for item in row['top']:
        values = item['value']
        jaipur_df_2["Features"].append(values)


jaipur_df_2 = pd.DataFrame(jaipur_df_2)

In [51]:
# new Dataframe to store required values
jaipur_df_3 = {"Comfort_and_Convenience": [], "Comfort_and_Convenience_type": []}

for index, row in jaipur_cars_df.iterrows():
    for item in row['data']:
        heading = item['heading']
        values = item['list'][0]['value']
        jaipur_df_3["Comfort_and_Convenience"].append(heading)
        jaipur_df_3["Comfort_and_Convenience_type"].append(values)

# Convert the dictionary to a DataFrame
jaipur_df_3 = pd.DataFrame(jaipur_df_3)

In [52]:
jaipur_cars_df=jaipur_cars_df.drop(['top','data'],axis=1)

In [53]:
jaipur_cars_df = json_normalize(jaipur_cars_df, 'new_car_specs')

# New Dataframe to store required values
jaipur_df_4 = {"Car_Specifications": [], "Values_for_Car_Specifications": []}

for index, row in jaipur_cars_df.iterrows():
    for item in row['top']:
        key=item['key']
        values = item['value']
        jaipur_df_4["Car_Specifications"].append(key)
        jaipur_df_4["Values_for_Car_Specifications"].append(values)

# Convert the dictionary to a DataFrame
jaipur_df_4 = pd.DataFrame(jaipur_df_4)

In [54]:
# New Dataframe to store required values
jaipur_df_5 = {"Feature_heading": [], "Feature_key_heading": [],"Feature_value":[]}

for index, row in jaipur_cars_df.iterrows():
    for item in row['data']:
        heading = item['subHeading']
        key=item['list'][0]['key']
        values = item['list'][0]['value']
        jaipur_df_5["Feature_heading"].append(heading)
        jaipur_df_5["Feature_key_heading"].append(key)
        jaipur_df_5["Feature_value"].append(values)

# Convert the dictionary to a DataFrame
jaipur_df_5 = pd.DataFrame(jaipur_df_5)

In [55]:
jaipur_cars_df = jaipur_cars_df.drop(['top','data'], axis=1)

In [56]:
# Merging all DataFrames with jaipur_cars_df


jaipur_cars_df = pd.merge(jaipur_cars_df, jaipur_df_1, how='left', left_index=True, right_index=True)

jaipur_cars_df = pd.merge(jaipur_cars_df, jaipur_df_2, how='left', left_index=True, right_index=True)

jaipur_cars_df = pd.merge(jaipur_cars_df, jaipur_df_3, how='left', left_index=True, right_index=True)

jaipur_cars_df = pd.merge(jaipur_cars_df, jaipur_df_4, how='left', left_index=True, right_index=True)

jaipur_cars_df = pd.merge(jaipur_cars_df, jaipur_df_5, how='left', left_index=True, right_index=True)

In [58]:
jaipur_cars_df['city']='Jaipur'

In [57]:
jaipur_cars_df= jaipur_cars_df.drop(['car_links','Image_link_of_car'],axis=1)

In [59]:
jaipur_cars_df

,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,Car_model,Year_of_car_manufacture,...,Values_for_Car_Info,Features,Comfort_and_Convenience,Comfort_and_Convenience_type,Car_Specifications,Values_for_Car_Specifications,Feature_heading,Feature_key_heading,Feature_value,city
0,0,Diesel,Hatchback,"1,20,000",Manual,2,2nd Owner,Hyundai,Hyundai i20,2015,...,2015,Power Steering,Comfort & Convenience,Power Steering,Mileage,22.54 kmpl,Engine,Color,Others,Jaipur
1,0,Petrol,Hatchback,"66,951",Manual,1,1st Owner,Maruti,Maruti Swift,2012,...,Third Party insurance,Power Windows Front,Interior,Air Conditioner,Engine,1396 CC,Dimensions,Length,3985mm,Jaipur
2,0,Petrol,Hatchback,"80,000",Automatic,2,2nd Owner,Maruti,Maruti Celerio,2016,...,Diesel,Air Conditioner,Exterior,Adjustable Head Lights,Max Power,88.73bhp,Miscellaneous,Gear Box,6 Speed,Jaipur
3,0,Petrol,Hatchback,"44,392",Manual,1,1st Owner,Hyundai,Hyundai Grand i10,2017,...,5 Seats,Heater,Safety,Anti Lock Braking System,Torque,219.7Nm,Engine,Color,White,Jaipur
4,0,Petrol,Hatchback,"40,000",Automatic,1,1st Owner,Maruti,Maruti Wagon R,2016,...,"1,20,000 Kms",Adjustable Head Lights,Entertainment & Communication,Cd Player,Wheel Size,16,Dimensions,Length,3845mm,Jaipur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Chevrolet,Chevrolet Beat,2011,...,5 Seats,Cd Player,Comfort & Convenience,Power Steering,Seats,5,Miscellaneous,Gear Box,5 Speed,Jaipur
1116,0,Petrol,Hatchback,"70,000",Manual,1,1st Owner,Maruti,Maruti Alto,2007,...,"25,446 Kms",Power Steering,Interior,Air Conditioner,Mileage,16.56 kmpl,Engine,Color,Others,Jaipur
1117,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Renault,Renault Kiger,2022,...,RJ45,Power Windows Front,Exterior,Adjustable Head Lights,Engine,1451 CC,Dimensions,Length,3999mm,Jaipur
1118,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Alto,2009,...,First Owner,Air Conditioner,Safety,Anti Lock Braking System,Max Power,141bhp,Miscellaneous,Gear Box,6 Speed,Jaipur
1119,0,Petrol,Hatchback,"80,000",Manual,1,1st Owner,Maruti,Maruti Baleno,2018,...,999 cc,Heater,Entertainment & Communication,Cd Player,Torque,250nm,Engine,Color,Others,Jaipur

In [60]:
# Saving the cleaned data
jaipur_cars_df.to_excel('Final_Jaipur_cars_list.xlsx')

In [3]:
# Preprosessing kolkata cars 

def json_normalize(df, column_name):
    import ast
    df[column_name] = df[column_name].apply(ast.literal_eval)
    df_normalized = pd.json_normalize(df[column_name])
    df_1 = pd.concat([df, df_normalized], axis=1)
    df_1 = df_1.drop(column_name, axis=1)
    return df_1

kol_cars_df = json_normalize(kk, 'new_car_detail')

In [4]:
# Mapping current column names to new names

column_rename_mapping = {
    'it': 'Ignition_type',
    'ft': 'Fuel_type',
    'bt': 'Body_type',
    'km': 'Kilometers_driven',
    'transmission': 'Transmission_type',
    'ownerNo': 'Number_of_previous_owners',
    'owner': 'Ownership_details',
    'oem': 'Original_Equipment_Manufacturer',
    'model': 'Car_model',
    'modelYear': 'Year_of_car_manufacture',
    'centralVariantId': 'Central_variant_ID',
    'variantName': 'Variant_name',
    'price': 'Price_of_the_used_car',
    'priceActual': 'Actual_price',
    'priceSaving': 'Price_saving_information',
    'priceFixedText': 'Fixed price details',
    'trendingText.imgUrl': 'Image_URL',
    'trendingText.heading': 'Trending_heading',
    'trendingText.desc': 'Trending_description'
}


kol_cars_df.rename(columns=column_rename_mapping, inplace=True)

In [5]:
kol_cars_df = json_normalize(kol_cars_df, 'new_car_overview')

# New Dataframe to store required values
kol_df_1 = {"Car_Info": [], "Values_for_Car_Info": [], "Image_link_of_car": []}

for index, row in kol_cars_df.iterrows():
    for item in row['top']:
        key = item['key']
        values = item['value']
        icon = item['icon']
        kol_df_1["Car_Info"].append(key)
        kol_df_1["Values_for_Car_Info"].append(values)
        kol_df_1["Image_link_of_car"].append(icon)


kol_df_1 = pd.DataFrame(kol_df_1)

In [6]:
# Deleting unwanted columns
kol_cars_df = kol_cars_df.drop(['top'], axis=1)

kol_cars_df = kol_cars_df.drop(['bottomData','heading'], axis=1)

In [7]:
kol_cars_df = json_normalize(kol_cars_df, 'new_car_feature')

# New Dataframe to store required values
kol_df_2 = { "Features": []}

for index, row in kol_cars_df.iterrows():
    for item in row['top']:
        values = item['value']
        kol_df_2["Features"].append(values)


kol_df_2 = pd.DataFrame(kol_df_2)

In [8]:
# New Dataframe to store required values
kol_df_3 = {"Comfort_and_Convenience": [], "Comfort_and_Convenience_type": []}

for index, row in kol_cars_df.iterrows():
    for item in row['data']:
        heading = item['heading']
        values = item['list'][0]['value']
        kol_df_3["Comfort_and_Convenience"].append(heading)
        kol_df_3["Comfort_and_Convenience_type"].append(values)


kol_df_3 = pd.DataFrame(kol_df_3)

In [9]:
# Deleting unwanted columns

kol_cars_df=kol_cars_df.drop(['top','data'],axis=1)

kol_cars_df = json_normalize(kol_cars_df, 'new_car_specs')

In [10]:
# New Dataframe to store required values
kol_df_4 = {"Car_Specifications": [], "Values_for_Car_Specifications": []}

for index, row in kol_cars_df.iterrows():
    for item in row['top']:
        key=item['key']
        values = item['value']
        kol_df_4["Car_Specifications"].append(key)
        kol_df_4["Values_for_Car_Specifications"].append(values)


kol_df_4 = pd.DataFrame(kol_df_4)

In [11]:
# New Dataframe to store required values
kol_df_5 = {"Feature_heading": [], "Feature_key_heading": [],"Feature_value":[]}

for index, row in kol_cars_df.iterrows():
    for item in row['data']:
        heading = item['subHeading']
        key=item['list'][0]['key']
        values = item['list'][0]['value']
        kol_df_5["Feature_heading"].append(heading)
        kol_df_5["Feature_key_heading"].append(key)
        kol_df_5["Feature_value"].append(values)


kol_df_5 = pd.DataFrame(kol_df_5)

In [12]:
# Droping unwanted columns
kol_cars_df = kol_cars_df.drop(['top','data'], axis=1)

In [13]:
# Merging all DataFrames with kol_cars_df


kol_cars_df = pd.merge(kol_cars_df, kol_df_1, how='left', left_index=True, right_index=True)

kol_cars_df = pd.merge(kol_cars_df, kol_df_2, how='left', left_index=True, right_index=True)

kol_cars_df = pd.merge(kol_cars_df, kol_df_3, how='left', left_index=True, right_index=True)

kol_cars_df = pd.merge(kol_cars_df, kol_df_4, how='left', left_index=True, right_index=True)

kol_cars_df = pd.merge(kol_cars_df, kol_df_5, how='left', left_index=True, right_index=True)

In [14]:
#Deleting unwanted columns and adding city column
kol_cars_df=kol_cars_df.drop(['car_links','Image_link_of_car'],axis=1)

kol_cars_df['city']= 'Kolkata'

In [15]:
kol_cars_df

,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,Car_model,Year_of_car_manufacture,...,Values_for_Car_Info,Features,Comfort_and_Convenience,Comfort_and_Convenience_type,Car_Specifications,Values_for_Car_Specifications,Feature_heading,Feature_key_heading,Feature_value,city
0,0,Petrol,Sedan,"70,000",Automatic,3,3rd Owner,Toyota,Toyota Camry,2014,...,2014,Power Steering,Comfort & Convenience,Power Steering,Mileage,19.16 kmpl,Engine,Color,White,Kolkata
1,0,Petrol,Hatchback,"23,981",Manual,1,1st Owner,Datsun,Datsun RediGO,2017,...,Third Party insurance,Power Windows Front,Interior,Air Conditioner,Engine,2494 CC,Dimensions,Length,4825mm,Kolkata
2,0,Petrol,SUV,"7,100",Automatic,1,1st Owner,Renault,Renault Kiger,2021,...,Petrol,Air Conditioner,Exterior,Adjustable Head Lights,Max Power,158.2bhp,Miscellaneous,Gear Box,6 Speed,Kolkata
3,0,Petrol,Hatchback,"71,574",Manual,2,2nd Owner,Hyundai,Hyundai i20,2011,...,5 Seats,Heater,Safety,Anti Lock Braking System,Torque,213Nm,Engine,Color,Red,Kolkata
4,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Audi,Audi Q3,2014,...,"70,000 Kms",Adjustable Head Lights,Entertainment & Communication,Cd Player,Wheel Size,17,Dimensions,Length,3429mm,Kolkata
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,Jan 2009,Air Conditioner,Exterior,Adjustable Head Lights,Max Power,67.05bhp,Engine,Color,Others,Kolkata
1377,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,Comprehensive,Heater,Safety,Centeral Locking,Torque,90Nm,Dimensions,Length,4395 mm,Kolkata
1378,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,Petrol,Adjustable Head Lights,Entertainment & Communication,Radio,Seats,5,Miscellaneous,Gear Box,4 Speed,Kolkata
1379,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,5 Seats,Fog Lights Front,Comfort & Convenience,Power Steering,Mileage,14.28 kmpl,Engine,Color,Golden,Kolkata
1380,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,"45,000 Kms",Anti Lock Braking System,Interior,Air Conditioner,Engine,1798 CC,Dimensions,Length,4386mm,Kolkata

In [16]:
#Saving preprocessed data

kol_cars_df.to_excel('Final_Kolkata_cars_list.xlsx')

In [30]:
ch

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Minivans', 'k...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1414,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1415,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1416,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1417,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1418,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [35]:
ch

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Minivans', 'k...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1414,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1415,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1416,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1417,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1418,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [36]:
# Preprosessing chennai cars 

def json_normalize(df, column_name):
    df[column_name] = df[column_name].apply(ast.literal_eval)
    df_normalized = pd.json_normalize(df[column_name])
    df_1 = pd.concat([df, df_normalized], axis=1)
    df_1 = df_1.drop(column_name, axis=1)
    return df_1

chennai_cars_df = json_normalize(ch, 'new_car_detail')

In [38]:
# Mapping current column names to new names

column_rename_mapping = {
    'it': 'Ignition_type',
    'ft': 'Fuel_type',
    'bt': 'Body_type',
    'km': 'Kilometers_driven',
    'transmission': 'Transmission_type',
    'ownerNo': 'Number_of_previous_owners',
    'owner': 'Ownership_details',
    'oem': 'Original_Equipment_Manufacturer',
    'model': 'Car_model',
    'modelYear': 'Year_of_car_manufacture',
    'centralVariantId': 'Central_variant_ID',
    'variantName': 'Variant_name',
    'price': 'Price_of_the_used_car',
    'priceActual': 'Actual_price',
    'priceSaving': 'Price_saving_information',
    'priceFixedText': 'Fixed price details',
    'trendingText.imgUrl': 'Image_URL',
    'trendingText.heading': 'Trending_heading',
    'trendingText.desc': 'Trending_description'
}


chennai_cars_df.rename(columns=column_rename_mapping, inplace=True)

In [40]:
chennai_cars_df = json_normalize(chennai_cars_df,'new_car_overview')

# New Dataframe to store required values
ch_df_1 = {"Car_Info": [], "Values_for_Car_Info": [], "Image_link_of_car": []}

for index, row in chennai_cars_df.iterrows():
    for item in row['top']:
        key = item['key']
        values = item['value']
        icon = item['icon']
        ch_df_1["Car_Info"].append(key)
        ch_df_1["Values_for_Car_Info"].append(values)
        ch_df_1["Image_link_of_car"].append(icon)


ch_df_1 = pd.DataFrame(ch_df_1)

In [42]:
# Deleting unwanted columns
chennai_cars_df = chennai_cars_df.drop(['top'], axis=1)

chennai_cars_df = chennai_cars_df.drop(['bottomData','heading'], axis=1)

In [44]:
chennai_cars_df = json_normalize(chennai_cars_df, 'new_car_feature')

# New Dataframe to store required values
ch_df_2 = { "Features": []}

for index, row in chennai_cars_df.iterrows():
    for item in row['top']:
        values = item['value']
        ch_df_2["Features"].append(values)


ch_df_2 = pd.DataFrame(ch_df_2)

In [45]:
# New Dataframe to store required values
ch_df_3 = {"Comfort_and_Convenience": [], "Comfort_and_Convenience_type": []}

for index, row in chennai_cars_df.iterrows():
    for item in row['data']:
        heading = item['heading']
        values = item['list'][0]['value']
        ch_df_3["Comfort_and_Convenience"].append(heading)
        ch_df_3["Comfort_and_Convenience_type"].append(values)


ch_df_3 = pd.DataFrame(ch_df_3)

In [46]:
 #Deleting unwanted columns

chennai_cars_df= chennai_cars_df.drop(['top','data'],axis=1)

In [49]:
chennai_cars_df = json_normalize(chennai_cars_df,'new_car_specs')

# New Dataframe to store required values
ch_df_4 = {"Car_Specifications": [], "Values_for_Car_Specifications": []}

for index, row in chennai_cars_df.iterrows():
    for item in row['top']:
        key=item['key']
        values = item['value']
        ch_df_4["Car_Specifications"].append(key)
        ch_df_4["Values_for_Car_Specifications"].append(values)


ch_df_4 = pd.DataFrame(ch_df_4)

In [50]:
# New Dataframe to store required values
ch_df_5 = {"Feature_heading": [], "Feature_key_heading": [],"Feature_value":[]}

for index, row in chennai_cars_df.iterrows():
    for item in row['data']:
        heading = item['subHeading']
        key=item['list'][0]['key']
        values = item['list'][0]['value']
        ch_df_5["Feature_heading"].append(heading)
        ch_df_5["Feature_key_heading"].append(key)
        ch_df_5["Feature_value"].append(values)


ch_df_5 = pd.DataFrame(ch_df_5)

In [51]:
# Droping unwanted columns
chennai_cars_df = chennai_cars_df.drop(['top','data'], axis=1)

In [52]:
# Merging all DataFrames with chennai_cars_df


chennai_cars_df = pd.merge(chennai_cars_df, ch_df_1, how='left', left_index=True, right_index=True)

chennai_cars_df = pd.merge(chennai_cars_df, ch_df_2, how='left', left_index=True, right_index=True)

chennai_cars_df = pd.merge(chennai_cars_df, ch_df_3, how='left', left_index=True, right_index=True)

chennai_cars_df = pd.merge(chennai_cars_df, ch_df_4, how='left', left_index=True, right_index=True)

chennai_cars_df = pd.merge(chennai_cars_df, ch_df_5, how='left', left_index=True, right_index=True)

In [53]:
#Deleting unwanted columns and adding city column
chennai_cars_df= chennai_cars_df.drop(['car_links','Image_link_of_car'],axis=1)

chennai_cars_df['city']= 'Chennai'

In [54]:
# Saving preprocessed data
chennai_cars_df.to_excel('Final_chennai_cars_list.xlsx')

In [56]:
# Preprosessing bangalore cars 

def json_normalize(df, column_name):
    import ast
    df[column_name] = df[column_name].apply(ast.literal_eval)
    df_normalized = pd.json_normalize(df[column_name])
    df_1 = pd.concat([df, df_normalized], axis=1)
    df_1 = df_1.drop(column_name, axis=1)
    return df_1

blr_cars_df = json_normalize(blr, 'new_car_detail')

In [57]:
# Mapping current column names to new names

column_rename_mapping = {
    'it': 'Ignition_type',
    'ft': 'Fuel_type',
    'bt': 'Body_type',
    'km': 'Kilometers_driven',
    'transmission': 'Transmission_type',
    'ownerNo': 'Number_of_previous_owners',
    'owner': 'Ownership_details',
    'oem': 'Original_Equipment_Manufacturer',
    'model': 'Car_model',
    'modelYear': 'Year_of_car_manufacture',
    'centralVariantId': 'Central_variant_ID',
    'variantName': 'Variant_name',
    'price': 'Price_of_the_used_car',
    'priceActual': 'Actual_price',
    'priceSaving': 'Price_saving_information',
    'priceFixedText': 'Fixed price details',
    'trendingText.imgUrl': 'Image_URL',
    'trendingText.heading': 'Trending_heading',
    'trendingText.desc': 'Trending_description'
}


blr_cars_df.rename(columns=column_rename_mapping, inplace=True)

In [58]:
blr_cars_df = json_normalize(blr_cars_df, 'new_car_overview')

# New Dataframe to store required values
blr_df_1 = {"Car_Info": [], "Values_for_Car_Info": [], "Image_link_of_car": []}

for index, row in blr_cars_df.iterrows():
    for item in row['top']:
        key = item['key']
        values = item['value']
        icon = item['icon']
        blr_df_1["Car_Info"].append(key)
        blr_df_1["Values_for_Car_Info"].append(values)
        blr_df_1["Image_link_of_car"].append(icon)


blr_df_1 = pd.DataFrame(blr_df_1)

In [59]:
# Droping unwanted columns

blr_cars_df = blr_cars_df.drop(['top'], axis=1)

blr_cars_df = blr_cars_df.drop(['bottomData','heading'], axis=1)

In [60]:
blr_cars_df = json_normalize(blr_cars_df, 'new_car_feature')


# New Dataframe to store required values
blr_df_2 = { "Features": []}

for index, row in blr_cars_df.iterrows():
    for item in row['top']:
        values = item['value']
        blr_df_2["Features"].append(values)


blr_df_2 = pd.DataFrame(blr_df_2)

In [61]:
# New Dataframe to store required values
blr_df_3 = {"Comfort_and_Convenience": [], "Comfort_and_Convenience_type": []}

for index, row in blr_cars_df.iterrows():
    for item in row['data']:
        heading = item['heading']
        values = item['list'][0]['value']
        blr_df_3["Comfort_and_Convenience"].append(heading)
        blr_df_3["Comfort_and_Convenience_type"].append(values)

blr_df_3 = pd.DataFrame(blr_df_3)

In [62]:
# droping columns
blr_cars_df= blr_cars_df.drop(['top','data'],axis=1)

In [64]:
blr_cars_df = json_normalize(blr_cars_df, 'new_car_specs')

# New Dataframe to store required values
blr_df_4 = {"Car_Specifications": [], "Values_for_Car_Specifications": []}

for index, row in blr_cars_df.iterrows():
    for item in row['top']:
        key=item['key']
        values = item['value']
        blr_df_4["Car_Specifications"].append(key)
        blr_df_4["Values_for_Car_Specifications"].append(values)

blr_df_4 = pd.DataFrame(blr_df_4)

In [65]:
# New Dataframe to store required values
blr_df_5 = {"Feature_heading": [], "Feature_key_heading": [],"Feature_value":[]}

for index, row in blr_cars_df.iterrows():
    for item in row['data']:
        heading = item['subHeading']
        key=item['list'][0]['key']
        values = item['list'][0]['value']
        blr_df_5["Feature_heading"].append(heading)
        blr_df_5["Feature_key_heading"].append(key)
        blr_df_5["Feature_value"].append(values)

blr_df_5 = pd.DataFrame(blr_df_5)

In [66]:
# Droping the top and data column
blr_cars_df = blr_cars_df.drop(['top','data'], axis=1)

In [67]:
# Merging all DataFrames with blr_cars_df


blr_cars_df = pd.merge(blr_cars_df, blr_df_1, how='left', left_index=True, right_index=True)

blr_cars_df = pd.merge(blr_cars_df, blr_df_2, how='left', left_index=True, right_index=True)

blr_cars_df = pd.merge(blr_cars_df, blr_df_3, how='left', left_index=True, right_index=True)

blr_cars_df = pd.merge(blr_cars_df, blr_df_4, how='left', left_index=True, right_index=True)

blr_cars_df = pd.merge(blr_cars_df, blr_df_5, how='left', left_index=True, right_index=True)

In [68]:
# Deleting unwanted columns and adding city column
blr_cars_df= blr_cars_df.drop(['car_links','Image_link_of_car'],axis=1)

blr_cars_df['city']= 'Bangalore'

In [69]:
# Saving preprocessed data
blr_cars_df.to_excel('Final_bangalore_cars_list.xlsx')

In [72]:
# importing all cleaned datas

chennai=pd.read_excel("Final_chennai_cars_list.xlsx")
bangalore=pd.read_excel("Final_bangalore_cars_list.xlsx")
hyderabad=pd.read_excel("Final_Hyderabad_cars_list.xlsx")
jaipur=pd.read_excel("Final_Jaipur_cars_list.xlsx")
kolkata=pd.read_excel("Final_Kolkata_cars_list.xlsx")
delhi=pd.read_excel("Final_Delhi_cars_list.xlsx")

In [73]:
# Combining all city into a df and checking for null values
Final_cars_list=pd.concat([chennai,bangalore,hyderabad,jaipur,kolkata,delhi],axis=0)

Final_cars_list.isnull().sum()/len(Final_cars_list)*100

Unnamed: 0                           0.000000
Ignition_type                        0.000000
Fuel_type                            0.000000
Body_type                            0.047795
Kilometers_driven                    0.000000
Transmission_type                    0.000000
Number_of_previous_owners            0.000000
Ownership_details                    0.000000
Original_Equipment_Manufacturer      0.000000
Car_model                            0.000000
Year_of_car_manufacture              0.000000
Central_variant_ID                   0.000000
Variant_name                         0.000000
Price_of_the_used_car                0.000000
Actual_price                        80.045406
Price_saving_information           100.000000
Fixed price details                100.000000
Image_URL                            0.000000
Trending_heading                     0.000000
Trending_description                 0.000000
heading                              0.000000
commonIcon                           0.000000
heading.1                            0.000000
commonIcon.1                       100.000000
Car_Info                             0.000000
Values_for_Car_Info                  0.011949
Features                             0.000000
Comfort_and_Convenience              0.000000
Comfort_and_Convenience_type         0.000000
Car_Specifications                   0.000000
Values_for_Car_Specifications        0.000000
Feature_heading                      0.000000
Feature_key_heading                  0.000000
Feature_value                        0.000000
city                                 0.000000
dtype: float64

In [74]:
Final_cars_list=Final_cars_list.drop(['Price_saving_information','Fixed price details','Actual_price'],axis=1)
Final_cars_list=Final_cars_list.drop(['commonIcon.1'],axis=1)

In [75]:
Final_cars_list.isnull().sum()/len(Final_cars_list)*100

Unnamed: 0                         0.000000
Ignition_type                      0.000000
Fuel_type                          0.000000
Body_type                          0.047795
Kilometers_driven                  0.000000
Transmission_type                  0.000000
Number_of_previous_owners          0.000000
Ownership_details                  0.000000
Original_Equipment_Manufacturer    0.000000
Car_model                          0.000000
Year_of_car_manufacture            0.000000
Central_variant_ID                 0.000000
Variant_name                       0.000000
Price_of_the_used_car              0.000000
Image_URL                          0.000000
Trending_heading                   0.000000
Trending_description               0.000000
heading                            0.000000
commonIcon                         0.000000
heading.1                          0.000000
Car_Info                           0.000000
Values_for_Car_Info                0.011949
Features                           0.000000
Comfort_and_Convenience            0.000000
Comfort_and_Convenience_type       0.000000
Car_Specifications                 0.000000
Values_for_Car_Specifications      0.000000
Feature_heading                    0.000000
Feature_key_heading                0.000000
Feature_value                      0.000000
city                               0.000000
dtype: float64

In [77]:
Final_cars_list=Final_cars_list.drop(['Trending_heading','heading','heading.1'],axis=1)
Final_cars_list=Final_cars_list.drop(['Trending_description'],axis=1)

In [78]:
car_info= Final_cars_list[['Car_Info','Values_for_Car_Info']]
car_info_df= car_info.T

In [79]:
Final_cars_list['Car_Info'].value_counts()
Final_cars_list['Values_for_Car_Info'].value_counts()

Values_for_Car_Info
5 Seats                  752
First Owner              607
Manual                   589
Petrol                   568
Third Party insurance    378
                        ...
18,432 Kms                 1
27,120 Kms                 1
41,705 Kms                 1
HR12                       1
41,200 Kms                 1
Name: count, Length: 929, dtype: int64

In [80]:
# Create a pivot table
Car_Info = Final_cars_list.pivot_table(index=Final_cars_list.index, columns='Car_Info', values='Values_for_Car_Info', aggfunc='first')
Car_Info.isnull().sum()/len(Car_Info)*100

Final_cars_list=Final_cars_list.drop(['Car_Info','Values_for_Car_Info'],axis=1)

Final_cars_list = Final_cars_list.reset_index(drop=True)
Car_Info = Car_Info.reset_index(drop=True)

In [81]:
# Concate the DataFrames along axis=1
Final_cars_list = pd.concat([Final_cars_list, Car_Info], axis=1)

Final_cars_list=Final_cars_list.drop(['Features'],axis=1)

Final_cars_list.columns

Index(['Unnamed: 0', 'Ignition_type', 'Fuel_type', 'Body_type',
       'Kilometers_driven', 'Transmission_type', 'Number_of_previous_owners',
       'Ownership_details', 'Original_Equipment_Manufacturer', 'Car_model',
       'Year_of_car_manufacture', 'Central_variant_ID', 'Variant_name',
       'Price_of_the_used_car', 'Image_URL', 'commonIcon',
       'Comfort_and_Convenience', 'Comfort_and_Convenience_type',
       'Car_Specifications', 'Values_for_Car_Specifications',
       'Feature_heading', 'Feature_key_heading', 'Feature_value', 'city',
       'Engine Displacement', 'Fuel Type', 'Insurance Validity', 'Kms Driven',
       'Ownership', 'RTO', 'Registration Year', 'Seats', 'Transmission',
       'Year of Manufacture'],
      dtype='object')

In [82]:
Comfort_Convenience = Final_cars_list.pivot_table(index=Final_cars_list.index, columns='Comfort_and_Convenience', values='Comfort_and_Convenience_type', aggfunc='first')
Comfort_Convenience.isnull().sum()/len(Comfort_Convenience)*100

Comfort_and_Convenience
Comfort & Convenience            79.543554
Entertainment & Communication    81.682399
Exterior                         79.579400
Interior                         79.555502
Safety                           79.639144
dtype: float64

In [83]:
Final_cars_list=Final_cars_list.drop(['Comfort_and_Convenience','Comfort_and_Convenience_type'],axis=1)
Final_cars_list = pd.concat([Final_cars_list, Comfort_Convenience], axis=1)

In [84]:
Car_Specifications = Final_cars_list.pivot_table(index=Final_cars_list.index, columns='Car_Specifications', values='Values_for_Car_Specifications', aggfunc='first')
Car_Specifications.isnull().sum()/len(Car_Specifications)*100

Car_Specifications
Engine        82.184251
Max Power     82.243996
Mileage       82.817541
Seats         82.255945
Torque        82.243996
Wheel Size    88.254272
dtype: float64

In [85]:
Final_cars_list=Final_cars_list.drop(['Car_Specifications','Values_for_Car_Specifications'],axis=1)
Final_cars_list = pd.concat([Final_cars_list, Car_Specifications], axis=1)

In [86]:
Final_cars_list=Final_cars_list.drop(['Feature_heading'],axis=1)

In [87]:
Car_features = Final_cars_list.pivot_table(index=Final_cars_list.index, columns='Feature_key_heading', values='Feature_value', aggfunc='first')
Car_features.isnull().sum()/len(Car_features)*100

Final_cars_list=Final_cars_list.drop(['Feature_key_heading','Feature_value'],axis=1)
Final_cars_list = pd.concat([Final_cars_list, Car_features], axis=1)

In [88]:
img_url=Final_cars_list[['commonIcon','Image_URL']]
Final_cars_list=Final_cars_list.drop(['commonIcon','Image_URL'],axis=1)

In [89]:
Final_cars_list=Final_cars_list.drop(['Unnamed: 0'],axis=1)
Final_cars_list.columns

Index(['Ignition_type', 'Fuel_type', 'Body_type', 'Kilometers_driven',
       'Transmission_type', 'Number_of_previous_owners', 'Ownership_details',
       'Original_Equipment_Manufacturer', 'Car_model',
       'Year_of_car_manufacture', 'Central_variant_ID', 'Variant_name',
       'Price_of_the_used_car', 'city', 'Engine Displacement', 'Fuel Type',
       'Insurance Validity', 'Kms Driven', 'Ownership', 'RTO',
       'Registration Year', 'Seats', 'Transmission', 'Year of Manufacture',
       'Comfort & Convenience', 'Entertainment & Communication', 'Exterior',
       'Interior', 'Safety', 'Engine', 'Max Power', 'Mileage', 'Seats',
       'Torque', 'Wheel Size', 'Color', 'Drive Type', 'Gear Box',
       'Kerb Weight', 'Length', 'Seating Capacity'],
      dtype='object')

In [90]:
# getting null percentage for all the columns
null_percentage = (Final_cars_list.isnull().sum() / len(Final_cars_list)) * 100
print("Percentage of null values for each column:")
print(null_percentage)

Percentage of null values for each column:
Ignition_type                       0.000000
Fuel_type                           0.000000
Body_type                           0.047795
Kilometers_driven                   0.000000
Transmission_type                   0.000000
Number_of_previous_owners           0.000000
Ownership_details                   0.000000
Original_Equipment_Manufacturer     0.000000
Car_model                           0.000000
Year_of_car_manufacture             0.000000
Central_variant_ID                  0.000000
Variant_name                        0.000000
Price_of_the_used_car               0.000000
city                                0.000000
Engine Displacement                93.404230
Fuel Type                          93.404230
Insurance Validity                 93.428128
Kms Driven                         93.404230
Ownership                          93.404230
RTO                                93.798542
Registration Year                  93.404230
Seats                              93.404230
Transmission                       93.404230
Year of Manufacture                93.428128
Comfort & Convenience              79.543554
Entertainment & Communication      81.682399
Exterior                           79.579400
Interior                           79.555502
Safety                             79.639144
Engine                             82.184251
Max Power                          82.243996
Mileage                            82.817541
Seats                              82.255945
Torque                             82.243996
Wheel Size                         88.254272
Color                              66.614888
Drive Type                         99.952205
Gear Box                           66.889712
Kerb Weight                        99.892460
Length                             66.841917
Seating Capacity                   99.808818
dtype: float64

In [91]:
## Setting an percentage so that to remove those columns
columns_to_remove = null_percentage[null_percentage >= 75].index

In [109]:
# Droping columns with null percentage >= 75%
Final_cars_list= Final_cars_list.drop(columns=columns_to_remove)
Final_cars_list.isnull().sum() / len(Final_cars_list) * 100

KeyError: "['Engine Displacement', 'Fuel Type', 'Insurance Validity', 'Kms Driven', 'Ownership', 'RTO', 'Registration Year', 'Seats', 'Transmission', 'Year of Manufacture', 'Comfort & Convenience', 'Entertainment & Communication', 'Exterior', 'Interior', 'Safety', 'Engine', 'Max Power', 'Mileage', 'Seats', 'Torque', 'Wheel Size', 'Drive Type', 'Kerb Weight', 'Seating Capacity'] not found in axis"

In [93]:
Final_df= Final_cars_list[['Car_model','Year_of_car_manufacture','Kilometers_driven','Number_of_previous_owners',
                          'Transmission_type','Fuel_type','Body_type','Color','Price_of_the_used_car','city']]

In [105]:
Final_df

,Car_model,Year_of_car_manufacture,Kilometers_driven,Number_of_previous_owners,Transmission_type,Fuel_type,Body_type,Color,Price_of_the_used_car,city
0,Kia Sonet,2022,"20,000",1,Automatic,Petrol,SUV,Black,â‚¹ 11.50 Lakh,Chennai
1,Maruti Eeco,2015,"20,687",1,Manual,Petrol,Minivans,NaN,â‚¹ 4.15 Lakh,Chennai
2,Nissan Magnite,2021,"30,000",1,Manual,Petrol,SUV,NaN,â‚¹ 7.50 Lakh,Chennai
3,Hyundai i10,2015,"59,247",1,Manual,Petrol,Hatchback,Grey,â‚¹ 3.98 Lakh,Chennai
4,Honda Jazz,2015,"50,000",1,Manual,Petrol,Hatchback,NaN,â‚¹ 5.50 Lakh,Chennai
...,...,...,...,...,...,...,...,...,...,...
8364,Honda City,2019,"60,000",1,Automatic,Petrol,Sedan,NaN,â‚¹ 9 Lakh,Delhi
8365,Kia Sonet,2021,"20,000",1,Manual,Petrol,SUV,Others,â‚¹ 9.50 Lakh,Delhi
8366,Hyundai Verna,2011,"60,000",1,Manual,Petrol,Sedan,NaN,â‚¹ 4.18 Lakh,Delhi
8367,Hyundai Creta,2019,"38,000",1,Manual,Diesel,SUV,NaN,â‚¹ 11.95 Lakh,Delhi
8368,MG Gloster,2023,"7,000",0,Automatic,Diesel,SUV,Pearl White,â‚¹ 46.40 Lakh,Delhi

In [108]:
Final_df['Body_type'].value_counts()

Body_type
Hatchback        3571
SUV              2225
Sedan            2174
MUV               352
Minivans           23
Coupe              10
Convertibles        6
Pickup Trucks       6
Hybrids             1
Wagon               1
Name: count, dtype: int64

In [107]:
# Calculate the mode of the 'Body_type' column
mode_body_type = Final_df['Body_type'].mode()[0]

# Fill missing values with the mode
Final_df['Body_type'].fillna(mode_body_type, inplace=True)

# Verify if all missing values are filled
print(Final_df['Body_type'].isnull().sum())

0

C:\Users\Vijay\AppData\Local\Temp\ipykernel_14996\3706746983.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_df['Body_type'].fillna(mode_body_type, inplace=True)

In [118]:
Final_df.isnull().sum()

Car_model                    0
Year_of_car_manufacture      0
Kilometers_driven            0
Number_of_previous_owners    0
Transmission_type            0
Fuel_type                    0
Body_type                    0
Price_of_the_used_car        0
city                         0
dtype: int64

In [117]:
Final_df.drop('Color',axis= 1, inplace=True)

C:\Users\Vijay\AppData\Local\Temp\ipykernel_14996\915566874.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_df.drop('Color',axis= 1, inplace=True)

In [1]:
Final_df.to_excel('Final_data.xlsx')

NameError: name 'Final_df' is not defined